### PR TITLE
644 primary ingredient missing when there are substitutes for ingredients in a meal

### LINKED ISSUE #644: [BUG] Primary ingredient missing when there are substitutes for ingredients in a meal
**Describe the bug**
Primary ingredient missing when there are substitutes for ingredients in a meal

**To Reproduce**
1. Go to 'Admin UI'
2. Click on '.Bread and Butter Pudding'
3. Check the ingredients list. This has Butter and Margarine as well as Apricot Jam, Raspberry Jam, Marmalade
4. Go to 'Mealplanner UI'
5. Click on 'Meals'
6. Search for Bread and Butter Pudding
7. Look at the ingredients
8. Butter, Apricot Jam are missing. Both are primary ingredients

**Expected behavior**
All ingredients should be displayed.

**Test Environment (please complete the following information):**
 - Browser and version [e.g. chrome, safari] Chrome
 - Platform [e.g. IDE, docker-compose, QA site] QA site

### PR DESCRIPTION
**Pull request by RLCASTRO**
**Describe the technical changes contained in this PR**
Fix the bug in the data displayed in the Ingredients table on the Meal page.

**Previous behaviour**
The table was being rendered with the wrong data

**New behaviour**
The table now displays the correct data from the database, as you can see in the images below.

**Meals page displaying the correct data**
image

**All the ingredients for this same meal in the database**
image

**Related issues addressed by this PR**
Fixes #644 

**Have the following been addressed?**
- [ ] Have test cases been created for all of the changes?
- [ ] Do all of the test cases pass?
- [ ] Has the testing been done using the default docker-compose environment?
- [ ] Are documentation changes required?
- [ ] Does this change break or alter existing behaviour?

### CODE REVIEW

File: mealplanner-ui/src/pages/Meals/Meal.tsx [hunk 1]
```diff
@@ -322,51 +310,44 @@ export const Meal = () => {
...
                                 </span>
                               </>
-                            ) : (
-                              <></>
                             )}
                           </td>
                           <td style={{ textAlign: "center", verticalAlign: "top" }}>
-                            {ingredient.quantity}
-                            {ingredient.substituteIngredient ? (
+                            {ingredient.substituteIngredientId === null && ingredient.quantity}
```
Comment (shanthisa) [inline mealplanner-ui/src/pages/Meals/Meal.tsx:334]: Why do we need this check for ingredient.quantity. Quantity exists irrespective of whether it is substitute Ingredient isnt it?

File: mealplanner-ui/src/pages/Meals/Meal.tsx [hunk 2]
```diff
@@ -322,51 +310,44 @@ export const Meal = () => {
...
                                 <br />
                               </>
-                            ) : (
-                              <></>
                             )}
                           </td>
                           <td style={{ paddingLeft: "0.5rem" }}>
-                            {ingredient.unit}
-                            {ingredient.substituteIngredient ? (
+                            {ingredient.substituteIngredientId === null && ingredient.unit}
```
Comment (shanthisa) [inline mealplanner-ui/src/pages/Meals/Meal.tsx:344]: Why do we need this check for ingredient.unit. Unit exists irrespective of whether it is substitute Ingredient isnt it?

**Review by shanthisa — CHANGES_REQUESTED** [review]
Please check the questions

File: mealplanner-ui/src/pages/Meals/Meal.tsx (hunk 1 above)
Comment (shanthisa) [reply mealplanner-ui/src/pages/Meals/Meal.tsx:334]: I understand because it is in a different line

**Review by shanthisa — APPROVED** [review]
LGTM 👍
